### ISSUE TITLE
Option to remove those lines?

### ISSUE THREAD

**Issue by mpkh** [viva64/how-to-use-pvs-studio-free#1]
I can work on it if that will be acceptable
note that I really think it will be better to have it included in this utility
because I'm sure people will run own shell scripts to `sed` those lines back

also in case if that will be rejected it will be much easier to replace this utility with some script which will be able to actually remove those lines back, and even wrap running pvs-analyser inside itself.

Thank you

**Comment by mpkh** [comment]
@AndreyKarpov okay... not acceptable
however note that closing issue without explanation is not very good practics

**Comment by AndreyKarpov** [comment]
The ability to remove comments from the source code will encourage the users to use the analyzer in a dishonest way. Therefore, we consider it unreasonable to add it.

You should insert these comments when you have already decided to use the analyzer on a regular basis. Please, use a demo version or request a temporary license key to try out the analyzer. 

In the next version of the analyzer this text passage will be added to the user agreement:

It is not allowed to add and remove the comments in the source code repeatedly. It is also not allowed to append comments multiple times and subsequently roll back the content of comments in source files to the initial state using version control system. Such actions are intended to evade the terms that the source should contain comments and are a violation of the analyzer usage agreement.

**Comment by mpkh** [comment]
@AndreyKarpov just to clear up things for me, do I understand it right: license will tell (in nutshell) if analyzer were used at least once - those comments should stick there forever?

**Comment by AndreyKarpov** [comment]
You can remove the comment any time. We want to forbid repetitive adding and removing the comments. When people start discussing, what is the best way to add and remove the comments, it’s clear that it is a dishonest way. We cannot be happy about this. We have decided to claim that we don’t’ consider such a way to be right. Yes, we cannot control that, but we rely on the honesty of programmers.
