### ISSUE TITLE
"add Java to Comments" problem

### ISSUE THREAD

**Issue by ivantaran** [viva64/how-to-use-pvs-studio-free#15]
after commit "add Java to Comments" pvs-studio-analyzer can't see comments for free use for this version: http://files.viva64.com/pvs-studio-6.26.28267.608-amd64.deb

**Comment by SvyatoslavRazmyslov** [comment]
Hello @ivantaran,

We have updated the utility after the PVS-Studio 6.26 release. You can take the last release of the utility "how-to-use-pvs-studio-free" [here](https://github.com/viva64/how-to-use-pvs-studio-free/releases) or wait until PVS-Studio 6.27 (it will be released within the next 1-2 weeks).
