### ISSUE TITLE
Help screen: Are the initial comments really enough to get it working on Linux?

### ISSUE THREAD

**Issue by philipp-classen** [viva64/how-to-use-pvs-studio-free#2]
I failed to get pvs-studio working on Linux. Actually, I don't think it is a bug in the script that adds the comments, but the help screen could benefit from a few clues for Linux users that have never used PVS before.

Here is a summary of my experience:

After I ran the tool (```how-to-use-pvs-studio-free -c 3 $(ack -f --cpp | grep -v '\.h$')```), it inserted comments in all of my source files:

>// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
>// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

The help screen says

> If you are using PVS-Studio for Linux, you do not need to do anything else besides adding comments to the source code. Just check your code.

That is also consistent with the official blog post that I read, so I expected everything is set up. Next, I ran

```pvs-studio-analyzer trace -- make```

It succeeded without errors, but when I ran "analyze", I only get encrypted(?!) outputs:

```$ pvs-studio-analyzer analyze 
[  0%] Analyzing: /tmp/ghost/ghost.cpp
Processing file /tmp/ghost/ghost.cpp
(oPk(jL8=o('8>=oU>o=}L;ib^%cuaa8acrGSG%
H-v->jc=L8aoc>UPu=co8cj289U2cvUa-U92u=c-=c'8>=-_uau_co8c9uc9U_ckaU'o-'u}c1oc-=c=hjju=ou_co8cau>UPucN$xNcvUa-U92u}c@uvu2%cJ
(oPk(jL8=o('8>=oU>o=}L;i[^%cuaa8acrGSG%
H-v->jc=L8aoc>UPu=co8cj289U2cvUa-U92u=c-=c'8>=-_uau_co8c9uc9U_ckaU'o-'u}c1oc-=c=hjju=ou_co8cau>UPucNOxNcvUa-U92u}c@uvu2%cJ
...
```
I tested it on Arch Linux with "PVS-Studio 6.11.20138.1". The help screen and the blog posts mention that for Visual Studio, you have to you a licence file:

> Name: PVS-Studio Free
> Key:  FREE-FREE-FREE-FREE

I have not used PVS-Studio before and I'm just guessing. Unfortunately, the error messages are not helpful:

```
$ pvs-studio
Cannot open configuration file PVS-Studio.cfg.
How to Launch the PVS-Studio Analyzer: http://www.viva64.com/en/d/0519/
$ touch PVS-Studio.cfg
$ pvs-studio
TUoU2cuaa8acu>'8h>ouau_
```

I'm quite sure that there is a problem in my setup. I tried to create a licence file, but I don't know the expected syntax and with those type of error messages, it is very hard to understand what is going on. :-(

Maybe I am missing something obvious, but at this point, I gave up.

**Comment by SvyatoslavRazmyslov** [comment]
For the _pvs-studio-analyzer analyze_ command you need to specify a file with the output file with the help of '-o' parameter:

`pvs-studio-analyzer analyze ... -o project.log ...`

Here is a list of commands that you will need  to get the analyzer report:

```
$ pvs-studio-analyzer trace -- make
$ pvs-studio-analyzer analyze -o /path/to/project.log -j<N>
$ plog-converter -a GA:1,2 -t tasklist -o /path/to/project.tasks /path/to/project.log
```

**Comment by philipp-classen** [comment]
Thanks a lot. I missed that there is the plog-converter tool. Now I see the output. :-)
