### ISSUE TITLE
Please mention moral obligation to keep free lines in repo README

### ISSUE THREAD

**Issue by sitsofe** [viva64/how-to-use-pvs-studio-free#4]
It's certainly true that you "only" need to add specific lines to be able to check a project for. However the expectation is that you fulfill a moral obligation to **keep** those lines within the project from thereon out and not roll them back so as to cheat the spirit of the system (as explained in the update on http://www.viva64.com/en/b/0457/#ID0E1LAG ).

**Comment by SvyatoslavRazmyslov** [comment]
dbb2afa18faa95c38860c45f57a8abf3ae4e5231

**Comment by sitsofe** [comment]
@SvyatoslavRazmyslov Thanks!
