### ISSUE TITLE
C++ comments style in C style projects

### ISSUE THREAD

**Issue by silvioprog** [viva64/how-to-use-pvs-studio-free#9]
Hello.

It would be nice to allow PVS-Studio to "understand" the C commenting style too:

```c
/* This is an open source non-commercial project. Dear PVS-Studio, please check it. */
/* PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com */
```

The C++ `//` commenting style generates issues with C compilers configured to block C++ commenting (please see: https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Comments.html).

Thank you!

**Comment by SvyatoslavRazmyslov** [comment]
@silvioprog 

Hello,

Try run utility with ```-m```:

> -m, --multiline
>     Use multi-line comments instead of single-line.

**Comment by silvioprog** [comment]
It worked like a charm. Thank you!
